# Tensor representation

## Simple example

In [1]:
import numpy as np

In [2]:
A = np.array([[0, 0, 0], [1, 0, 1], [1, 0, 0]])
E = np.array([[1, 1, 0], [-1, 0, -1], [0, -1, 1]])

In [3]:
A

array([[0, 0, 0],
       [1, 0, 1],
       [1, 0, 0]])

In [4]:
e1 = np.array([[0, 0, 0], [1, 0, 0], [0, 0, 0]])
e2 = np.array([[0, 0, 0], [0, 0, 0], [1, 0, 0]])
e3 = np.array([[0, 0, 0], [0, 0, 1], [0, 0, 0]])

In [5]:
T = np.array([e1,e2,e3])

In [6]:
T

array([[[0, 0, 0],
        [1, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0],
        [1, 0, 0]],

       [[0, 0, 0],
        [0, 0, 1],
        [0, 0, 0]]])

In [8]:
np.sum(T, axis=0)

array([[0, 0, 0],
       [1, 0, 1],
       [1, 0, 0]])

In [9]:
T@E

array([[[ 0,  0,  0],
        [ 1,  1,  0],
        [ 0,  0,  0]],

       [[ 0,  0,  0],
        [ 0,  0,  0],
        [ 1,  1,  0]],

       [[ 0,  0,  0],
        [ 0, -1,  1],
        [ 0,  0,  0]]])

In [17]:
np.tensordot(T, E, axes=1)

array([[[ 0,  0,  0],
        [ 1,  1,  0],
        [ 0,  0,  0]],

       [[ 0,  0,  0],
        [ 0,  0,  0],
        [ 1,  1,  0]],

       [[ 0,  0,  0],
        [ 0, -1,  1],
        [ 0,  0,  0]]])

In [18]:
x_e1 = np.array([[0, -1, 0], [1, 0, 0], [0, 0, 0]])
x_e2 = np.array([[0, 0, -1], [0, 0, 0], [1, 0, 0]])
x_e3 = np.array([[0, 0, 0], [0, 0, 1], [0, -1, 0]])

In [19]:
Tx = np.array([x_e1,x_e2,x_e3])

In [21]:
np.sum(Tx, axis=0)

array([[ 0, -1, -1],
       [ 1,  0,  1],
       [ 1, -1,  0]])

In [56]:
np.tensordot(Tx, E, axes=2)

array([-2,  0,  0])

array([1, 1, 1])

In [27]:
np.max(Tx, 0)

array([[0, 0, 0],
       [1, 0, 1],
       [1, 0, 0]])

In [29]:
Tx

array([[[ 0, -1,  0],
        [ 1,  0,  0],
        [ 0,  0,  0]],

       [[ 0,  0, -1],
        [ 0,  0,  0],
        [ 1,  0,  0]],

       [[ 0,  0,  0],
        [ 0,  0,  1],
        [ 0, -1,  0]]])

In [31]:
TxP = np.max(Tx, 0)
TxN = np.min(Tx, 0)

In [71]:
np.sum(Tx, axis=1).T

array([[ 1,  1,  0],
       [-1,  0, -1],
       [ 0, -1,  1]])

In [78]:
np.max(Tx, 0)

array([[0, 0, 0],
       [1, 0, 1],
       [1, 0, 0]])

## Other example

In [82]:
x1_e1 = np.array([[0, 1, 0], [-1, 0, 0], [0, 0, 0]])
x1_e2 = np.array([[0, 0, 0], [0, 0, 1], [0, -1, 0]])
x1_e3 = np.array([[0, 0, -1], [0, 0, 0], [1, 0, 0]])

In [83]:
Tx1 = np.array([x1_e1,x1_e2,x1_e3])

In [85]:
np.max(Tx1, 0)

array([[0, 1, 0],
       [0, 0, 1],
       [1, 0, 0]])

In [89]:
np.sum(Tx1, axis=1).T

array([[-1,  0,  1],
       [ 1, -1,  0],
       [ 0,  1, -1]])

## Other examples (4 nodes)

In [198]:
x2_e1 = np.array([[0, 1, 0, 0],
                  [-1, 0, 0, 0],
                  [0, 0, 0, 0],
                  [0, 0, 0, 0]])
x2_e2 = np.array([[0, 0, 0, 0],
                  [0, 0, 1, 0],
                  [0, -1, 0, 0],
                  [0, 0, 0, 0]])
x2_e3 = np.array([[0, 0, 0, 0],
                  [0, 0, 0, 0],
                  [0, 0, 0, 1],
                  [0, 0, -1, 0]])
x2_e4 = np.array([[0, 0, 0, -1],
                  [0, 0, 0, 0],
                  [0, 0, 0, 0],
                  [1, 0, 0, 0]])
x2_e5 = np.array([[0, 0, -1, 0],
                  [0, 0, 0, 0],
                  [1, 0, 0, 0],
                  [0, 0, 0, 0]])

In [199]:
Tx2 = np.array([x2_e1, x2_e2, x2_e3, x2_e4, x2_e5])

In [200]:
np.sum(Tx2, axis=1)

array([[-1,  1,  0,  0],
       [ 0, -1,  1,  0],
       [ 0,  0, -1,  1],
       [ 1,  0,  0, -1],
       [ 1,  0, -1,  0]])

In [201]:
np.sum(Tx2, axis=1).T

array([[-1,  0,  0,  1,  1],
       [ 1, -1,  0,  0,  0],
       [ 0,  1, -1,  0, -1],
       [ 0,  0,  1, -1,  0]])

In [202]:
np.abs(Tx2)

array([[[0, 1, 0, 0],
        [1, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0]],

       [[0, 0, 0, 0],
        [0, 0, 1, 0],
        [0, 1, 0, 0],
        [0, 0, 0, 0]],

       [[0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 1],
        [0, 0, 1, 0]],

       [[0, 0, 0, 1],
        [0, 0, 0, 0],
        [0, 0, 0, 0],
        [1, 0, 0, 0]],

       [[0, 0, 1, 0],
        [0, 0, 0, 0],
        [1, 0, 0, 0],
        [0, 0, 0, 0]]])

In [203]:
Q, R = np.linalg.qr(Tx2)

In [205]:
Tx2 @ Q

array([[[ 1.,  0.,  0.,  0.],
        [ 0., -1.,  0.,  0.],
        [ 0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.]],

       [[ 0.,  0.,  0.,  0.],
        [ 0.,  1.,  0.,  0.],
        [ 0.,  0., -1.,  0.],
        [ 0.,  0.,  0.,  0.]],

       [[ 0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.],
        [ 0.,  0.,  1.,  0.],
        [ 0.,  0.,  0., -1.]],

       [[ 1.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.],
        [ 0.,  0.,  0., -1.]],

       [[ 1.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.],
        [ 0.,  0., -1.,  0.],
        [ 0.,  0.,  0.,  0.]]])

In [206]:
np.sum(R, axis=2).T

array([[-1.,  0.,  0., -1., -1.],
       [ 1., -1.,  0.,  0.,  0.],
       [ 0.,  1., -1.,  0.,  1.],
       [ 0.,  0.,  1.,  1.,  0.]])

In [207]:
s, v,d, =np.linalg.svd(Tx2)

In [208]:
Tx2 @ s

array([[[ 1.,  0.,  0.,  0.],
        [ 0., -1.,  0.,  0.],
        [ 0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.]],

       [[ 0.,  0.,  0.,  0.],
        [ 0.,  1.,  0.,  0.],
        [-1.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.]],

       [[ 0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.],
        [ 1.,  0.,  0.,  0.],
        [ 0., -1.,  0.,  0.]],

       [[ 1.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.],
        [ 0., -1.,  0.,  0.]],

       [[ 1.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.],
        [ 0., -1.,  0.,  0.],
        [ 0.,  0.,  0.,  0.]]])

In [209]:
np.dot(Tx2, d)

array([[[[ 0.,  1.,  0.,  0.],
         [ 0., -1.,  0.,  0.],
         [ 0.,  0.,  0.,  1.],
         [ 0.,  0.,  0.,  1.],
         [ 0.,  0.,  1.,  0.]],

        [[ 1.,  0.,  0.,  0.],
         [ 0.,  0., -1.,  0.],
         [ 0.,  0.,  1.,  0.],
         [ 1.,  0.,  0.,  0.],
         [ 1.,  0.,  0.,  0.]],

        [[ 0.,  0.,  0.,  0.],
         [ 0.,  0.,  0.,  0.],
         [ 0.,  0.,  0.,  0.],
         [ 0.,  0.,  0.,  0.],
         [ 0.,  0.,  0.,  0.]],

        [[ 0.,  0.,  0.,  0.],
         [ 0.,  0.,  0.,  0.],
         [ 0.,  0.,  0.,  0.],
         [ 0.,  0.,  0.,  0.],
         [ 0.,  0.,  0.,  0.]]],


       [[[ 0.,  0.,  0.,  0.],
         [ 0.,  0.,  0.,  0.],
         [ 0.,  0.,  0.,  0.],
         [ 0.,  0.,  0.,  0.],
         [ 0.,  0.,  0.,  0.]],

        [[ 0.,  0.,  1.,  0.],
         [ 1.,  0.,  0.,  0.],
         [ 1.,  0.,  0.,  0.],
         [ 0.,  1.,  0.,  0.],
         [ 0.,  1.,  0.,  0.]],

        [[ 0., -1.,  0.,  0.],
         [ 0.,  1.,  0., 

In [212]:
np.sum(np.dot(Tx2, d), axis=1)

array([[[ 1.,  1.,  0.,  0.],
        [ 0., -1., -1.,  0.],
        [ 0.,  0.,  1.,  1.],
        [ 1.,  0.,  0.,  1.],
        [ 1.,  0.,  1.,  0.]],

       [[ 0., -1.,  1.,  0.],
        [ 1.,  1.,  0.,  0.],
        [ 1.,  0.,  0., -1.],
        [ 0.,  1.,  0., -1.],
        [ 0.,  1., -1.,  0.]],

       [[ 0.,  0., -1.,  1.],
        [-1.,  0.,  0.,  1.],
        [-1.,  1.,  0.,  0.],
        [ 0., -1.,  1.,  0.],
        [ 0., -1.,  0.,  1.]],

       [[-1.,  0.,  0., -1.],
        [ 0.,  0.,  1., -1.],
        [ 0., -1., -1.,  0.],
        [-1.,  0., -1.,  0.],
        [-1.,  0.,  0., -1.]],

       [[-1.,  0., -1.,  0.],
        [-1.,  0.,  1.,  0.],
        [-1.,  0., -1.,  0.],
        [-1., -1.,  0.,  0.],
        [-1., -1.,  0.,  0.]]])

In [216]:
np.sum(Tx2 @ s, axis=0)

array([[ 3.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.],
       [ 0., -1.,  0.,  0.],
       [ 0., -2.,  0.,  0.]])

In [220]:
diag_x2 = np.eye(4) * np.sum(Tx2, axis=1)[:, np.newaxis, :]

In [221]:
diag_x2 = np.where(diag_x2 > 0, diag_x2, 0)

In [222]:
diag_x2

array([[[0., 0., 0., 0.],
        [0., 1., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 1., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 1.]],

       [[1., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[1., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [223]:
Lx = diag_x2 - np.where(Tx2 > 0, Tx2, 0)

In [224]:
proj_Lx = np.sum(Lx, axis=0)

In [225]:
np.trace(proj_Lx)*np.log(np.trace(proj_Lx))

8.047189562170502

In [227]:
e, v = np.linalg.eig(Lx)

In [240]:
-e*np.log(e)

C:\Users\keret\AppData\Local\Temp\ipykernel_23376\727744675.py:1: RuntimeWarning: divide by zero encountered in log
  -e*np.log(e)
C:\Users\keret\AppData\Local\Temp\ipykernel_23376\727744675.py:1: RuntimeWarning: invalid value encountered in multiply
  -e*np.log(e)


array([[nan, -0., nan, nan],
       [nan, nan, -0., nan],
       [nan, nan, nan, -0.],
       [nan, -0., nan, nan],
       [nan, -0., nan, nan]])

In [241]:
e

array([[0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.],
       [0., 1., 0., 0.],
       [0., 1., 0., 0.]])

In [242]:
Lx

array([[[ 0., -1.,  0.,  0.],
        [ 0.,  1.,  0.,  0.],
        [ 0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.]],

       [[ 0.,  0.,  0.,  0.],
        [ 0.,  0., -1.,  0.],
        [ 0.,  0.,  1.,  0.],
        [ 0.,  0.,  0.,  0.]],

       [[ 0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.],
        [ 0.,  0.,  0., -1.],
        [ 0.,  0.,  0.,  1.]],

       [[ 1.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.],
        [-1.,  0.,  0.,  0.]],

       [[ 1.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.],
        [-1.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.]]])

## Factor graph

In [243]:
x2_e1 = np.array([[0, 0, 0, -1, -1],
                  [0, 0, 0, -1, -1],
                  [0, 0, 0, 0, 0],
                  [1, 1, 0, 0, 0],
                  [1, 1, 0, 0, 0]])
x2_e2 = np.array([[0, 0, 0, 0, 0],
                  [0, 0, 0, 0, 1],
                  [0, 0, 0, 0, 1],
                  [0, 0, 0, 0, 0],
                  [0, -1, -1, 0, 0]])
Tx = np.array([x2_e1,x2_e2])

In [247]:
diag_x3 = np.eye(5) * np.sum(Tx, axis=1)[:, np.newaxis, :]
diag_x3 = np.where(diag_x3 > 0, diag_x3, 0)

In [255]:
diag_x3

array([[[2., 0., 0., 0., 0.],
        [0., 2., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 2.]]])

In [253]:
Lx = diag_x3 - np.where(Tx > 0, Tx, 0)

In [254]:
Lx

array([[[ 2.,  0.,  0.,  0.,  0.],
        [ 0.,  2.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.,  0.],
        [-1., -1.,  0.,  0.,  0.],
        [-1., -1.,  0.,  0.,  0.]],

       [[ 0.,  0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0., -1.],
        [ 0.,  0.,  0.,  0., -1.],
        [ 0.,  0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.,  2.]]])

In [256]:
e, v = np.linalg.eig(Lx)

In [257]:
e

array([[0., 0., 2., 2., 0.],
       [0., 0., 0., 0., 2.]])

In [260]:
-e*np.log2(e)

C:\Users\keret\AppData\Local\Temp\ipykernel_23376\3587633688.py:1: RuntimeWarning: divide by zero encountered in log2
  -e*np.log2(e)
C:\Users\keret\AppData\Local\Temp\ipykernel_23376\3587633688.py:1: RuntimeWarning: invalid value encountered in multiply
  -e*np.log2(e)


array([[nan, nan, -2., -2., nan],
       [nan, nan, nan, nan, -2.]])

In [261]:
proj_Lx = np.sum(Lx, axis=0)

In [262]:
np.trace(proj_Lx)*np.log(np.trace(proj_Lx))

10.75055681536833